ControlAsignacionMaquinaria/Controllers/AsignacionController.cs
using ControlAsignacionMaquinariaBLL.BLL;
using ControlAsignacionMaquinariaBLL.ModelosParciales;
using System.Web.Mvc;

namespace ControlAsignacionMaquinaria.Controllers
{
    public class AsignacionController : Controller
    {
        // GET: Asignacion
        /// <summary>
        /// Vista Asignacion
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
        #region JSON Get-Post
        /// <summary>
        /// Registro de las asignaciones de maquinaria
        /// </summary>
        /// <param name="asignacion">Objeto AsignacionEmpleado</param>
        /// <returns>JSON bool</returns>
        public JsonResult nuevaAsignacion(AsignacionEmpleado asignacion)
        {
            bool objRetorno;
            objRetorno = AsignacionBLL.editarAsignacion(asignacion);
            return Json(objRetorno, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

ControlAsignacionMaquinaria/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControlAsignacionMaquinaria.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashborad
        /// <summary>
        /// Vista Principal
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
    }
}

ControlAsignacionMaquinaria/Controllers/EmpleadoController.cs
using ControlAsignacionMaquinariaBLL.BLL;
using ControlAsignacionMaquinariaBLL.DB;
using System.Collections.Generic;
using System.Web.Mvc;

namespace ControlAsignacionMaquinaria.Controllers
{
    public class EmpleadoController : Controller
    {
        // GET: Empleado
        /// <summary>
        /// Vista Empleado
        /// </summary>
        /// <returns>lista Empleados</returns>
        public ActionResult Index()
        {
            List<Asi_Empleado> listaEmpleado = EmpleadoBLL.listaEmpleados();
            return View(listaEmpleado);
        }

        #region JSON Get-Post
        /// <summary>
        /// Consulta datos del empleado
        /// </summary>
        /// <param name="empleado">objeto Empleado</param>
        /// <returns>lista con los datos del empleado JSON</returns>
        public JsonResult consultarEmpleado(Asi_Empleado empleado)
        {
            Asi_Empleado objRetorno = EmpleadoBLL.consultarEmpleado(empleado);
            Asi_Empleado objeto = new Asi_Empleado();
            objeto.empId = objRetorno.empId;
            objeto.empNombre = objRetorno.empNombre;
            objeto.empCargo = objRetorno.empCargo;
            objeto.empCedula = objRetorno.empCedula;
            objeto.empArea = objRetorno.empArea;
            objeto.empFechaCreacion = objRetorno.empFechaCreacion;
            objeto.empEstado = objRetorno.empEstado;
 
            return Json(objeto, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// Registro de un nuevo Empleado
        /// </summary>
        /// <param name="empleado">Objeto empleado</param>
        /// <returns>JSON bool</returns>
        public JsonResult nuevoEmpleado(Asi_Empleado empleado)
        {
            bool objRetorno;
            objRetorno = EmpleadoBLL.crearEmpleado(empleado);
            return Json(objRetorno, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// Editar Empleado
        /// </summary>
        /// <param name="empleado">Objeto Empleado</param>
        /// <returns>JSON bool</returns>
        public JsonResult editarEmpleado(Asi_Empleado empleado)
        {
            bool objRetorno;
            objRetorno = EmpleadoBLL.editarEmpleado(empleado);
            return Json(objRetorno, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// Eliminar Empleado
        /// </summary>
        /// <param name="empleado">Objeto Empleado</param>
        /// <returns>JSON bool</returns>
        public JsonResult eliminarEmpleado(Asi_Empleado empleado)
        {
            bool objRetorno;
            objRetorno = EmpleadoBLL.eliminarEmpleado(empleado);
            return Json(objRetorno, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// Consulta de todos los Empleado
        /// </summary>
        /// <returns>Lista JSON con los empleados</returns>
        public JsonResult consultarEmpleadoJSON()
        {
            List<Asi_Empleado> lista = EmpleadoBLL.listaEmpleadosActivos();
            List<Asi_Empleado> objRetorno = new List<Asi_Empleado>();
            foreach (var item in lista)
            {
                Asi_Empleado objeto = new Asi_Empleado();
                objeto.empId = item.empId;
                objeto.empNombre = item.empNombre;
                objeto.empCedula = item.empCedula;
                objRetorno.Add(objeto);
            }

            return Json(objRetorno, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

ControlAsignacionMaquinaria/Controllers/ResumenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControlAsignacionMaquinaria.Controllers
{
    public class ResumenController : Controller
    {
        // GET: Resumen
        /// <summary>
        /// Vista Resumen
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }
    }
}

ControlAsignacionMaquinaria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
    @*<link rel="shortcut icon" href="img/favicon.png">*@
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/bootstrap-reset.css" rel="stylesheet" />
    <link href="~/Content/css/slidebars.css" rel="stylesheet" />
    <link href="~/Content/assets/toastr-master/toastr.css" rel="stylesheet" />
    <link href="~/Content/assets/jquery-multi-select/css/multi-select.css" rel="stylesheet" />
    <link href="~/Content/assets/select2/css/select2.min.css" rel="stylesheet" />
    <link href="~/Content/assets/select2/css/select2.css" rel="stylesheet" />
    <link href="~/Content/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen" />
    @*<link rel="stylesheet" href="~/Contenedor/css/owl.carousel.css" type="text/css">*@
    <!--custom css-->
    <link href="~/Content/css/style.css" rel="stylesheet" />
    <link href="~/Content/css/style-responsive.css" rel="stylesheet" />

    @RenderSection("css", required: false)


</head>

<body id="body">

    <section id="container" class="">
        <!--header start-->
        <header class="header white-bg">
            <div class="sidebar-toggle-box">
                <i class="fa fa-bars"></i>
            </div>
            <!--logo start-->
            <a href="@Url.Action("Index","Dashboard")" class="logo">
                Asignacion
            </a>
            <!--logo end-->
            <div class="nav notify-row" id="top_menu">
                <!--  notification start -->
                <ul class="nav top-menu">
                    <!-- settings start -->
                    <li class="dropdown">
                    </li>
                </ul>
                <!--  notification end -->
            </div>
            <div class="top-nav ">

                <ul class="nav pull-right top-menu">
                    <li class="dropdown">

                    </li>


                </ul>

            </div>
        </header>
        <!--header end-->
        <!--sidebar start-->
        <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu" id="nav-accordion">

                    <li>
                        <a href="@Url.Action("Index","Empleado")">
                            <i class="fa fa-users"></i>
                            <span>Empleados</span>
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("Index","Maquinaria")">
                            <i class="fa fa-cog"></i>
                            <span>Maquinaria</span>
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("Index","Asignacion")">
                            <i class="fa fa-check-circle"></i>
                            <span>Asignaciones</span>
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("Index","Resumen")">
                            <i class="fa fa-list"></i>
                            <span>Resumen</span>
                        </a>
                    </li>

                    @*<li class="sub-menu">
                            <a href="javascript:;">
                                <i class="fa fa-laptop"></i>
                                <span>Layouts</span>
                            </a>
                            <ul class="sub">
                                <li><a href="boxed_page.html">Boxed Page</a></li>
                                <li><a href="horizontal_menu.html">Horizontal Menu</a></li>
                                <li><a href="header-color.html">Different Color Top bar</a></li>
                                <li><a href="mega_menu.html">Mega Menu</a></li>
                                <li><a href="language_switch_bar.html">Language Switch Bar</a></li>
                                <li><a href="email_template.html" target="_blank">Email Template</a></li>
                            </ul>
                        </li>*@



                    <!--multi level menu start-->
                    @*<li class="sub-menu">
                            <a href="javascript:;">
                                <i class="fa fa-sitemap"></i>
                                <span>Multi level Menu</span>
                            </a>
                            <ul class="sub">
                                <li><a href="javascript:;">Menu Item 1</a></li>
                                <li class="sub-menu">
                                    <a href="boxed_page.html">Menu Item 2</a>
                                    <ul class="sub">
                                        <li><a href="javascript:;">Menu Item 2.1</a></li>
                                        <li class="sub-menu">
                                            <a href="javascript:;">Menu Item 3</a>
                                            <ul class="sub">
                                                <li><a href="javascript:;">Menu Item 3.1</a></li>
                                                <li><a href="javascript:;">Menu Item 3.2</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>*@
                    <!--multi level menu end-->

                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->
        <!--main content start-->
        <!-- page start-->
        @RenderBody()
        <!-- page end-->
        <!--main content end-->
        <!-- Right Slidebar start -->
        <div class="sb-slidebar sb-right sb-style-overlay">
            <h5 class="side-title">Online Customers</h5>
            <ul class="quick-chat-list">
            </ul>
            <h5 class="side-title"> pending Task</h5>
            <ul class="p-task tasks-bar">
                <li>
                    <a href="#">
                        <div class="task-info">
                            <div class="desc">Dashboard v1.3</div>
                            <div class="percent">40%</div>
                        </div>
                        <div class="progress">
                            <div style="width: 40%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="40" role="progressbar" class="progress-bar progress-bar-striped bg-success">
                                <span class="sr-only">40% Complete (success)</span>
                            </div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="task-info">
                            <div class="desc">Database Update</div>
                            <div class="percent">60%</div>
                        </div>
                        <div class="progress">
                            <div style="width: 60%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="60" role="progressbar" class="progress-bar progress-bar-striped bg-warning">
                                <span class="sr-only">60% Complete (warning)</span>
                            </div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="task-info">
                            <div class="desc">Iphone Development</div>
                            <div class="percent">87%</div>
                        </div>
                        <div class="progress">
                            <div style="width: 87%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="20" role="progressbar" class="progress-bar progress-bar-striped bg-info">
                                <span class="sr-only">87% Complete</span>
                            </div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="task-info">
                            <div class="desc">Mobile App</div>
                            <div class="percent">33%</div>
                        </div>
                        <div class="progress">
                            <div style="width: 33%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="80" role="progressbar" class="progress-bar progress-bar-striped bg-danger">
                                <span class="sr-only">33% Complete (danger)</span>
                            </div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="task-info">
                            <div class="desc">Dashboard v1.3</div>
                            <div class="percent">45%</div>
                        </div>
                        <div class="progress">
                            <div style="width: 45%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="45" role="progressbar" class="progress-bar progress-bar-striped">
                                <span class="sr-only">45% Complete</span>
                            </div>
                        </div>

                    </a>
                </li>
                <li class="external">
                    <a href="#">See All Tasks</a>
                </li>
            </ul>
        </div>
        <!-- Modal Recarga-->
        <div class="modal fade" id="modalEsperarRecarga" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" data-backdrop="static">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content" style="background-color:transparent">
                    <div class="modal-body">
                        <div class="form-group">
                            <div class="row" style="text-align:center">
                                <div class="col-lg-12">
                                    <button class="btn" style="border-radius:9px;font-size:50px; color:white" id="btnCargarInformacion"><i></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- modal -->
        <!-- Right Slidebar end -->
        <!--footer start-->
        <footer class="site-footer">
            <div class="text-center">
                @DateTime.Now.Year &copy;.
                <a href="#" class="go-top">
                    <i class="fa fa-angle-up"></i>
                </a>
            </div>
        </footer>
        <!--footer end-->
    </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="~/Content/js/jquery.js"></script>
    <script src="~/Content/js/bootstrap.bundle.min.js"></script>
    <script src="~/Content/js/jquery.scrollTo.min.js"></script>
    <script src="~/Content/js/slidebars.min.js"></script>
    <script src="~/Content/js/jquery.nicescroll.js"></script>
    <script src="~/Content/js/respond.min.js"></script>

    <!-- js placed at the end of the document so the pages load faster -->
    <script class="include" type="text/javascript" src="~/Content/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="~/Content/js/jquery.sparkline.js" type="text/javascript"></script>
    <script src="~/Content/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js"></script>
    <script src="~/Content/js/owl.carousel.js"></script>
    <script src="~/Content/js/jquery.customSelect.min.js"></script>

    <script src="~/Content/assets/toastr-master/toastr.js"></script>
    <script src="~/Content/assets/jquery-multi-select/js/jquery.multi-select.js"></script>
    <script src="~/Content/assets/jquery-multi-select/js/jquery.quicksearch.js"></script>
    <script src="~/Content/assets/select2/js/select2.full.min.js"></script>
    <script src="~/Content/assets/select2/js/select2.js"></script>

    <!--script for this page-->
    <script src="~/Content/js/sparkline-chart.js"></script>
    <script src="~/Content/js/easy-pie-chart.js"></script>
    @*<script src="~/Content/js/count.js"></script>*@
    <script src="~/Content/js/common-scripts.js"></script>
    @*<script src="~/JsExperiencia/Global/Validaciones.js"></script>*@
    @RenderSection("scripts", required: false)

</body>
</html>